/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.awt.event.KeyEvent;
import java.applet.AudioClip;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
/**
 *
 * @author OLIVER
 */
public class frm_calculadora extends javax.swing.JFrame {

    private String pantalla = "0";
    private String operacion = "nula";
    private double proceso, resultado;
    private boolean activado = true;
    private boolean punto = true;
    /**
     * Creates new form frm_calculadora
     */
    public frm_calculadora() {
        initComponents();
        //menu_opciones.add("Nuevo");
        //menu_opciones.add("Historial");
        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
        File archivo; //reg
        FileWriter escribir; //reg
        PrintWriter linea; //reg
        archivo = new File("bitacoraCalculadora.txt"); //reg
        if(!archivo.exists()){  //reg
            try{
                archivo.createNewFile();
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.close();
                escribir.close();
            }catch(IOException e){
                System.out.println("Error de archivo");
            }
        }else{
            try{
                //System.out.println("El archivo ya se ha creado anteriormente");
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.close();
                escribir.close();
            }catch(IOException e){
                System.out.println("Error de archivo");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btn_uno = new javax.swing.JButton();
        txt_calcu = new javax.swing.JTextField();
        btn_dos = new javax.swing.JButton();
        btn_tres = new javax.swing.JButton();
        btn_cuatro = new javax.swing.JButton();
        btn_cinco = new javax.swing.JButton();
        btn_seis = new javax.swing.JButton();
        btn_siete = new javax.swing.JButton();
        btn_ocho = new javax.swing.JButton();
        btn_nueve = new javax.swing.JButton();
        lbl_proceso = new javax.swing.JLabel();
        btn_suma = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_multi = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        btn_cero = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        menu_barra = new javax.swing.JMenuBar();
        menu_opciones = new javax.swing.JMenu();
        item_nuevo = new javax.swing.JMenuItem();
        item_historial = new javax.swing.JMenuItem();
        menu_ayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        escritorio.setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));

        btn_uno.setBackground(new java.awt.Color(204, 0, 255));
        btn_uno.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        btn_uno.setForeground(new java.awt.Color(0, 255, 204));
        btn_uno.setText("1");
        btn_uno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_unoMouseClicked(evt);
            }
        });
        btn_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_unoActionPerformed(evt);
            }
        });

        txt_calcu.setEditable(false);
        txt_calcu.setBackground(new java.awt.Color(102, 102, 255));
        txt_calcu.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        txt_calcu.setForeground(new java.awt.Color(255, 255, 255));
        txt_calcu.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_calcu.setText("0");
        txt_calcu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_calcu.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txt_calcu.setSelectionColor(new java.awt.Color(51, 255, 0));
        txt_calcu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_calcuKeyReleased(evt);
            }
        });

        btn_dos.setBackground(new java.awt.Color(204, 0, 255));
        btn_dos.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        btn_dos.setForeground(new java.awt.Color(0, 255, 204));
        btn_dos.setText("2");
        btn_dos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dosMouseClicked(evt);
            }
        });
        btn_dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dosActionPerformed(evt);
            }
        });

        btn_tres.setBackground(new java.awt.Color(204, 0, 255));
        btn_tres.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        btn_tres.setForeground(new java.awt.Color(0, 255, 204));
        btn_tres.setText("3");
        btn_tres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tresMouseClicked(evt);
            }
        });
        btn_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tresActionPerformed(evt);
            }
        });

        btn_cuatro.setBackground(new java.awt.Color(204, 0, 255));
        btn_cuatro.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        btn_cuatro.setForeground(new java.awt.Color(0, 255, 204));
        btn_cuatro.setText("4");
        btn_cuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cuatroMouseClicked(evt);
            }
        });
        btn_cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuatroActionPerformed(evt);
            }
        });

        btn_cinco.setBackground(new java.awt.Color(204, 0, 255));
        btn_cinco.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        btn_cinco.setForeground(new java.awt.Color(0, 255, 204));
        btn_cinco.setText("5");
        btn_cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cincoMouseClicked(evt);
            }
        });
        btn_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cincoActionPerformed(evt);
            }
        });

        btn_seis.setBackground(new java.awt.Color(204, 0, 255));
        btn_seis.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        btn_seis.setForeground(new java.awt.Color(0, 255, 204));
        btn_seis.setText("6");
        btn_seis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_seisMouseClicked(evt);
            }
        });
        btn_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seisActionPerformed(evt);
            }
        });

        btn_siete.setBackground(new java.awt.Color(204, 0, 255));
        btn_siete.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        btn_siete.setForeground(new java.awt.Color(0, 255, 204));
        btn_siete.setText("7");
        btn_siete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sieteMouseClicked(evt);
            }
        });
        btn_siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sieteActionPerformed(evt);
            }
        });

        btn_ocho.setBackground(new java.awt.Color(204, 0, 255));
        btn_ocho.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        btn_ocho.setForeground(new java.awt.Color(0, 255, 204));
        btn_ocho.setText("8");
        btn_ocho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ochoMouseClicked(evt);
            }
        });
        btn_ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ochoActionPerformed(evt);
            }
        });

        btn_nueve.setBackground(new java.awt.Color(204, 0, 255));
        btn_nueve.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        btn_nueve.setForeground(new java.awt.Color(0, 255, 204));
        btn_nueve.setText("9");
        btn_nueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nueveMouseClicked(evt);
            }
        });
        btn_nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nueveActionPerformed(evt);
            }
        });

        lbl_proceso.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_proceso.setForeground(new java.awt.Color(0, 255, 0));
        lbl_proceso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_calcu)
                    .addComponent(lbl_proceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 122, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lbl_proceso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_calcu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        btn_suma.setBackground(new java.awt.Color(204, 0, 255));
        btn_suma.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        btn_suma.setText("+");
        btn_suma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sumaMouseClicked(evt);
            }
        });
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });

        btn_resta.setBackground(new java.awt.Color(204, 0, 255));
        btn_resta.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        btn_resta.setText("-");
        btn_resta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_restaMouseClicked(evt);
            }
        });
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });

        btn_multi.setBackground(new java.awt.Color(204, 0, 255));
        btn_multi.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        btn_multi.setText("*");
        btn_multi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_multiMouseClicked(evt);
            }
        });
        btn_multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiActionPerformed(evt);
            }
        });

        btn_division.setBackground(new java.awt.Color(204, 0, 255));
        btn_division.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        btn_division.setText("/");
        btn_division.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_divisionMouseClicked(evt);
            }
        });
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });

        btn_cero.setBackground(new java.awt.Color(204, 0, 255));
        btn_cero.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        btn_cero.setForeground(new java.awt.Color(0, 255, 204));
        btn_cero.setText("0");
        btn_cero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ceroMouseClicked(evt);
            }
        });
        btn_cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ceroActionPerformed(evt);
            }
        });

        btn_punto.setBackground(new java.awt.Color(204, 0, 255));
        btn_punto.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        btn_punto.setForeground(new java.awt.Color(0, 255, 204));
        btn_punto.setText(".");
        btn_punto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_puntoMouseClicked(evt);
            }
        });
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        btn_igual.setBackground(new java.awt.Color(204, 0, 255));
        btn_igual.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        btn_igual.setText("=");
        btn_igual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_igualMouseClicked(evt);
            }
        });
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });

        escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btn_suma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btn_resta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btn_multi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btn_division, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btn_cero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btn_punto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btn_igual, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addComponent(btn_cero, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_division, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(escritorioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_division, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_cero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(escritorioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        menu_barra.setBackground(new java.awt.Color(0, 0, 0));
        menu_barra.setBorder(null);
        menu_barra.setForeground(new java.awt.Color(255, 255, 255));

        menu_opciones.setBackground(new java.awt.Color(0, 0, 0));
        menu_opciones.setForeground(new java.awt.Color(255, 255, 255));
        menu_opciones.setText("Opciones");
        menu_opciones.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        item_nuevo.setBackground(new java.awt.Color(0, 0, 0));
        item_nuevo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        item_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        item_nuevo.setText("Nuevo");
        item_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_nuevoActionPerformed(evt);
            }
        });
        menu_opciones.add(item_nuevo);

        item_historial.setBackground(new java.awt.Color(0, 0, 0));
        item_historial.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        item_historial.setForeground(new java.awt.Color(255, 255, 255));
        item_historial.setText("Historial");
        item_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_historialActionPerformed(evt);
            }
        });
        menu_opciones.add(item_historial);

        menu_barra.add(menu_opciones);

        menu_ayuda.setBackground(new java.awt.Color(0, 0, 0));
        menu_ayuda.setForeground(new java.awt.Color(255, 255, 255));
        menu_ayuda.setText("Ayuda");
        menu_ayuda.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        menu_ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_ayudaMouseClicked(evt);
            }
        });
        menu_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ayudaActionPerformed(evt);
            }
        });
        menu_ayuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                menu_ayudaKeyReleased(evt);
            }
        });
        menu_barra.add(menu_ayuda);

        setJMenuBar(menu_barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_unoActionPerformed
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
        if(txt_calcu.getText().equals("0")||txt_calcu.getText().equals("")){
            //txt_calcu.setText("1");
            pantalla = "1";
        }else{
            //txt_calcu.setText(txt_calcu.getText()+"1");
            pantalla += "1";
        }
        //txt_calcu.replaceSelection("1");
        activado = true;
        txt_calcu.setText(pantalla);
        activado = true;
    }//GEN-LAST:event_btn_unoActionPerformed

    private void btn_dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dosActionPerformed
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
        if(txt_calcu.getText().equals("0")||txt_calcu.getText().equals("")){
            pantalla = "2";
        }else{
            pantalla += "2";
        }
        activado = true;
        txt_calcu.setText(pantalla);
        activado = true;
    }//GEN-LAST:event_btn_dosActionPerformed

    private void btn_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tresActionPerformed
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
        if(txt_calcu.getText().equals("0")||txt_calcu.getText().equals("")){
            pantalla = "3";
        }else{
            pantalla += "3";
        }
        activado = true;
        txt_calcu.setText(pantalla);
        activado = true;
    }//GEN-LAST:event_btn_tresActionPerformed

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
        if(activado == true){
            proceso = Double.parseDouble(pantalla);
            lbl_proceso.setText(pantalla + " + ");
            pantalla = "0";
            txt_calcu.setText("0");
            operacion = "sumar";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuatroActionPerformed
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
        if(txt_calcu.getText().equals("0")||txt_calcu.getText().equals("")){
            pantalla = "4";
        }else{
            pantalla += "4";
        }
        activado = true;
        txt_calcu.setText(pantalla);
        activado = true;
    }//GEN-LAST:event_btn_cuatroActionPerformed

    private void btn_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cincoActionPerformed
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
        if(txt_calcu.getText().equals("0")||txt_calcu.getText().equals("")){
            pantalla = "5";
        }else{
            pantalla += "5";
        }
        activado = true;
        txt_calcu.setText(pantalla);
        activado = true;
    }//GEN-LAST:event_btn_cincoActionPerformed

    private void btn_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seisActionPerformed
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
        if(txt_calcu.getText().equals("0")||txt_calcu.getText().equals("")){
            pantalla = "6";
        }else{
            pantalla += "6";
        }
        activado = true;
        txt_calcu.setText(pantalla);
        activado = true;
    }//GEN-LAST:event_btn_seisActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
         if(activado == true){
            proceso = Double.parseDouble(pantalla);
            lbl_proceso.setText(pantalla + " - ");
            pantalla = "0";
            txt_calcu.setText("0");
            operacion = "restar";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sieteActionPerformed
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
        if(txt_calcu.getText().equals("0")||txt_calcu.getText().equals("")){
            pantalla = "7";
        }else{
            pantalla += "7";
        }
        activado = true;
        txt_calcu.setText(pantalla);
        activado = true;
    }//GEN-LAST:event_btn_sieteActionPerformed

    private void btn_ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ochoActionPerformed
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
        if(txt_calcu.getText().equals("0")||txt_calcu.getText().equals("")){
            pantalla = "8";
        }else{
            pantalla += "8";
        }
        activado = true;
        txt_calcu.setText(pantalla);
        activado = true;
    }//GEN-LAST:event_btn_ochoActionPerformed

    private void btn_nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nueveActionPerformed
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
        if(txt_calcu.getText().equals("0")||txt_calcu.getText().equals("")){
            pantalla = "9";
        }else{
            pantalla += "9";
        }
        activado = true;
        txt_calcu.setText(pantalla);
        activado = true;
    }//GEN-LAST:event_btn_nueveActionPerformed

    private void btn_multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiActionPerformed
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
        if(activado == true){
            proceso = Double.parseDouble(pantalla);
            lbl_proceso.setText(pantalla + " * ");
            pantalla = "0";
            txt_calcu.setText("0");
            operacion = "multiplicar";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_btn_multiActionPerformed

    private void btn_ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ceroActionPerformed
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
        if(txt_calcu.getText().equals("0")||txt_calcu.getText().equals("")){
            pantalla = "0";
        }else{
            pantalla += "0";
        }
        activado = true;
        txt_calcu.setText(pantalla);
        activado = true;
    }//GEN-LAST:event_btn_ceroActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
        if(punto == true){
            if(pantalla.equals("")){
                pantalla="0.";
            }else{
                pantalla += ".";
            }
        }
        txt_calcu.setText(pantalla);
        punto = false;
    }//GEN-LAST:event_btn_puntoActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        // TODO add your handling code here:
        File archivo; //reg
        FileWriter escribir; //reg
        PrintWriter linea; //reg
        archivo = new File("bitacoraCalculadora.txt"); //reg
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
        double procesond;
        if(operacion.equals("nula")){
            txt_calcu.setText(pantalla);
        }
        else if(operacion.equals("sumar")){
            procesond = Double.parseDouble(pantalla);
            resultado = proceso + procesond;
            txt_calcu.setText(String.format("% .2f", resultado));
            pantalla = String.valueOf(resultado);
            operacion = "nula";
            try{ //reg
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.print(String.valueOf(proceso)+"\n");
                linea.print("+\n");
                linea.print(String.valueOf(procesond)+"\n");
                linea.print(String.valueOf(resultado)+"\n");
                linea.close();
                escribir.close();
            }catch(IOException e){
                System.out.println("Error de archivo");
            }
        }
        else if(operacion.equals("restar")){
            procesond = Double.parseDouble(pantalla);
            resultado = proceso - procesond;
            txt_calcu.setText(String.format("% .2f", resultado));
            pantalla = String.valueOf(resultado);
            operacion = "nula";
            try{ //reg
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.print(String.valueOf(proceso)+"\n");
                linea.print("-\n");
                linea.print(String.valueOf(procesond)+"\n");
                linea.print(String.valueOf(resultado)+"\n");
                linea.close();
                escribir.close();
            }catch(IOException e){
                System.out.println("Error de archivo");
            }
        }
        else if(operacion.equals("multiplicar")){
            procesond = Double.parseDouble(pantalla);
            resultado = proceso * procesond;
            txt_calcu.setText(String.format("% .2f", resultado));
            pantalla = String.valueOf(resultado);
            operacion = "nula";
            try{ //reg
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.print(String.valueOf(proceso)+"\n");
                linea.print("*\n");
                linea.print(String.valueOf(procesond)+"\n");
                linea.print(String.valueOf(resultado)+"\n");
                linea.close();
                escribir.close();
            }catch(IOException e){
                System.out.println("Error de archivo");
            }
        }
        else if(operacion.equals("dividir")){
            procesond = Double.parseDouble(pantalla);
            if(procesond == 0){
                txt_calcu.setText("Invalido");
            }else{
                resultado = proceso / procesond; 
                txt_calcu.setText(String.format("% .2f", resultado));
                pantalla = String.valueOf(resultado);
                operacion = "nula";
                try{ //reg
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.print(String.valueOf(proceso)+"\n");
                linea.print("/\n");
                linea.print(String.valueOf(procesond)+"\n");
                linea.print(String.valueOf(resultado)+"\n");
                linea.close();
                escribir.close();
                }catch(IOException e){
                 System.out.println("Error de archivo");
                }
            }
        }
        
        
        lbl_proceso.setText("");
        activado = true;
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/vista/BEEP.wav"));
        sound.play();
        if(activado == true){
            proceso = Double.parseDouble(pantalla);
            lbl_proceso.setText(pantalla + " / ");
            pantalla = "0";
            txt_calcu.setText("0");
            operacion = "dividir";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_btn_divisionActionPerformed

    private void btn_unoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_unoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_unoMouseClicked

    private void btn_dosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dosMouseClicked
        
    }//GEN-LAST:event_btn_dosMouseClicked

    private void btn_tresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tresMouseClicked
        
    }//GEN-LAST:event_btn_tresMouseClicked

    private void btn_sumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sumaMouseClicked
        
    }//GEN-LAST:event_btn_sumaMouseClicked

    private void btn_cuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cuatroMouseClicked
        
    }//GEN-LAST:event_btn_cuatroMouseClicked

    private void btn_cincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cincoMouseClicked
        
    }//GEN-LAST:event_btn_cincoMouseClicked

    private void btn_seisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seisMouseClicked
        
    }//GEN-LAST:event_btn_seisMouseClicked

    private void btn_restaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_restaMouseClicked
       
    }//GEN-LAST:event_btn_restaMouseClicked

    private void btn_sieteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sieteMouseClicked
        
    }//GEN-LAST:event_btn_sieteMouseClicked

    private void btn_ochoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ochoMouseClicked
        
    }//GEN-LAST:event_btn_ochoMouseClicked

    private void btn_nueveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nueveMouseClicked
       
    }//GEN-LAST:event_btn_nueveMouseClicked

    private void btn_multiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_multiMouseClicked
        
    }//GEN-LAST:event_btn_multiMouseClicked

    private void btn_ceroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ceroMouseClicked
        
    }//GEN-LAST:event_btn_ceroMouseClicked

    private void btn_puntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_puntoMouseClicked
        
    }//GEN-LAST:event_btn_puntoMouseClicked

    private void btn_igualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_igualMouseClicked
        
    }//GEN-LAST:event_btn_igualMouseClicked

    private void btn_divisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_divisionMouseClicked
        
    }//GEN-LAST:event_btn_divisionMouseClicked

    private void txt_calcuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_calcuKeyReleased
        // TODO add your handling code here:
        char tecla=evt.getKeyChar();
        
        if(tecla==KeyEvent.VK_MINUS)
        {
            btn_resta.doClick();
        }
        else if(tecla=='+')
        {
            btn_suma.doClick();
        }
        else if(tecla=='*')
        {
            btn_multi.doClick();
        }
        else if(tecla=='/')
        {
            btn_division.doClick();
        }
        else if(tecla=='='||tecla==KeyEvent.VK_ENTER) //Se va a acceder al boton igual con = o con la tecla enter
        {
            btn_igual.doClick();
        }
        else if(tecla == KeyEvent.VK_1)
        {
            btn_uno.doClick();
        }
        else if(tecla == KeyEvent.VK_2)
        {
            btn_dos.doClick();
        }
        else if(tecla == KeyEvent.VK_3)
        {
            btn_tres.doClick();
        }
        else if(tecla == KeyEvent.VK_4)
        {
            btn_cuatro.doClick();
        }
        else if(tecla == KeyEvent.VK_5)
        {
            btn_cinco.doClick();
        }
        else if(tecla == KeyEvent.VK_6)
        {
            btn_seis.doClick();
        }
        else if(tecla == KeyEvent.VK_7)
        {
            btn_siete.doClick();
        }
        else if(tecla == KeyEvent.VK_8)
        {
            btn_ocho.doClick();
        }
        else if(tecla == KeyEvent.VK_9)
        {
            btn_nueve.doClick();
        }
        else if(tecla == KeyEvent.VK_0)
        {
            btn_cero.doClick();
        }
        else if(tecla == '.')
        {
            btn_punto.doClick();
        }
        else{
            txt_calcu.setText("Invalido"); //Toda tecla que no sea numerica va a ser invalidada
        }
    }//GEN-LAST:event_txt_calcuKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        char tecla=evt.getKeyChar();
        
        if(tecla==KeyEvent.VK_MINUS)
        {
            btn_resta.doClick();
        }
        else if(tecla=='+')
        {
            btn_suma.doClick();
        }
        else if(tecla=='*')
        {
            btn_multi.doClick();
        }
        else if(tecla=='/')
        {
            btn_division.doClick();
        }
        else if(tecla=='='||tecla==KeyEvent.VK_ENTER) //Se va a acceder al boton igual con = o con la tecla enter
        {
            btn_igual.doClick();
        }
        else if(tecla == KeyEvent.VK_1)
        {
            btn_uno.doClick();
        }
        else if(tecla == KeyEvent.VK_2)
        {
            btn_dos.doClick();
        }
        else if(tecla == KeyEvent.VK_3)
        {
            btn_tres.doClick();
        }
        else if(tecla == KeyEvent.VK_4)
        {
            btn_cuatro.doClick();
        }
        else if(tecla == KeyEvent.VK_5)
        {
            btn_cinco.doClick();
        }
        else if(tecla == KeyEvent.VK_6)
        {
            btn_seis.doClick();
        }
        else if(tecla == KeyEvent.VK_7)
        {
            btn_siete.doClick();
        }
        else if(tecla == KeyEvent.VK_8)
        {
            btn_ocho.doClick();
        }
        else if(tecla == KeyEvent.VK_9)
        {
            btn_nueve.doClick();
        }
        else if(tecla == KeyEvent.VK_0)
        {
            btn_cero.doClick();
        }
        else if(tecla == '.')
        {
            btn_punto.doClick();
        }
        else{
            txt_calcu.setText("Invalido"); //Toda tecla que no sea numerica va a ser invalidada
        }
    }//GEN-LAST:event_formKeyPressed

    private void item_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_historialActionPerformed
        ifrm_historial ventana = new ifrm_historial();
        escritorio.add(ventana);
        ventana.show();
        
    }//GEN-LAST:event_item_historialActionPerformed

    private void item_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_nuevoActionPerformed
        // TODO add your handling code here:
        String pantalla = "0";
        operacion = "nula";
        proceso = 0; 
        resultado = 0;
        activado = true;
        punto = true;
        txt_calcu.setText("0");
        lbl_proceso.setText("");
        File archivo; //reg
        FileWriter escribir; //reg
        PrintWriter linea; //reg
        archivo = new File("bitacoraCalculadora.txt"); //reg
        try{ //reg
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.print("Nuevo\n");
                linea.close();
                escribir.close();
            }catch(IOException e){
                System.out.println("Error de archivo");
            }
    }//GEN-LAST:event_item_nuevoActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formKeyReleased

    private void menu_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ayudaActionPerformed
        // TODO add your handling code here:
        /*Frm_ayu ventana = new Frm_ayu();
        escritorio.add(ventana);
        ventana.show();*/
    }//GEN-LAST:event_menu_ayudaActionPerformed

    private void menu_ayudaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menu_ayudaKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menu_ayudaKeyReleased

    private void menu_ayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_ayudaMouseClicked
        // TODO add your handling code here:
        Frm_ayu ventana = new Frm_ayu();
        escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_menu_ayudaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnC;
    private javax.swing.JButton btn_cero;
    private javax.swing.JButton btn_cinco;
    private javax.swing.JButton btn_cuatro;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_dos;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_multi;
    private javax.swing.JButton btn_nueve;
    private javax.swing.JButton btn_ocho;
    private javax.swing.JButton btn_punto;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_seis;
    private javax.swing.JButton btn_siete;
    private javax.swing.JButton btn_suma;
    private javax.swing.JButton btn_tres;
    private javax.swing.JButton btn_uno;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel etiquetaMuestra;
    private javax.swing.JLabel etiquetaNumeros;
    private javax.swing.JMenuItem item_historial;
    private javax.swing.JMenuItem item_nuevo;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_proceso;
    private javax.swing.JMenu menu_ayuda;
    private javax.swing.JMenuBar menu_barra;
    private javax.swing.JMenu menu_opciones;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txt_calcu;
    // End of variables declaration//GEN-END:variables
}
