/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
/**
 *
 * @author david
 */
public class ifrm_historial extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrm_historial
     */
    public ifrm_historial() {
        initComponents();
        this.setTitle("Historial bitacoraCalculadora.txt");
        File archivo;
        try{
            final BufferedReader lector = new BufferedReader(new FileReader("bitacoraCalculadora.txt"));
            String line = "";
            while ((line = lector.readLine()) != null){
                //txt_mostrar.setText(line);
                txt_mostrar.append(line +"\n");
            }lector.close();
        }catch(FileNotFoundException e){
            e.printStackTrace();
        } catch(IOException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_mostrar = new javax.swing.JScrollPane();
        txt_mostrar = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setMaximizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt_mostrar.setEditable(false);
        txt_mostrar.setBackground(new java.awt.Color(51, 51, 51));
        txt_mostrar.setColumns(20);
        txt_mostrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_mostrar.setForeground(new java.awt.Color(255, 255, 255));
        txt_mostrar.setRows(5);
        txt_mostrar.setSelectionColor(new java.awt.Color(51, 255, 0));
        pn_mostrar.setViewportView(txt_mostrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane pn_mostrar;
    private javax.swing.JTextArea txt_mostrar;
    // End of variables declaration//GEN-END:variables
}
